import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Header";
import Footer from "@/components/navbar/Footer";
import { CartProvider } from "@/Contexts/CartContext";
import { AuthProvider } from "@/Contexts/AuthContext"; // ← اضافه کردن AuthProvider
import { UserProvider } from "@/modules/food/hooks/useAdmin";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* ← اضافه کردن AuthProvider */}
          <CartProvider>
            <UserProvider> {/* اگر هنوز نیاز است */}
              <Navbar />
              {children}
              <Footer />
            </UserProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}